In [1]:
import numpy as np

In [6]:
ze = np.zeros(10)
print(ze)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
ones = np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
fives = np.ones(1*10)
print(fives)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
a=np.arange(0,9)
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
np.identity(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.random.normal(0,1,1)

array([0.06657192])

In [30]:
np.random.normal(0,1,25)

array([ 0.70763136,  0.97710385,  0.24958889,  0.15287678,  1.27026103,
        0.01120146, -0.36550204, -0.59184586, -0.88486355,  0.24156651,
       -1.23399873,  2.59490304,  0.28039448,  0.62215871, -0.979114  ,
        0.55021497,  0.39667179, -0.51049751, -0.03033078,  0.69796777,
        1.16944196,  0.31587537,  0.18331814, -0.59952944, -0.24611868])

In [31]:
np.arange(.01,1.01,.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [35]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [61]:
mat = np.arange(1,26).reshape(5,5)
print(mat)
print(mat[2:5,1:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [64]:
print(mat[3,4])

20


In [69]:
print(mat[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [72]:
print(mat[4])

[21 22 23 24 25]


In [74]:
print(mat[3:5])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [81]:
print(np.sum(mat))

325


In [80]:
print(np.std(mat))

7.211102550927978


In [84]:
print(np.sum(mat,axis=0))

[55 60 65 70 75]
